### ISSUE TITLE
[BUG] F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [DATL4G/BurningSeries-Android#88]
```
  - versionName: 6.0.0
    versionCode: 600
    commit: 994e14da42e36a4b6a9878be8e224d097c97decf
    subdir: composeApp
    gradle:
      - yes
    prebuild: sed -i -e '/jogamp/d' -e '/jetbrains/d' ../build.gradle.kts ../settings.gradle.kts
    scanignore:
      - firebase
```

fails at `gradle clean`
```
...
> Configure project :
e: file:///home/vagrant/build/dev.datlag.burningseries/build.gradle.kts:49:20: Unresolved reference: KotlinCompile
e: file:///home/vagrant/build/dev.datlag.burningseries/build.gradle.kts:50:9: Unresolved reference: compilerOptions
e: file:///home/vagrant/build/dev.datlag.burningseries/build.gradle.kts:51:13: Unresolved reference: jvmTarget
e: file:///home/vagrant/build/dev.datlag.burningseries/build.gradle.kts:51:27: Unresolved reference: JvmTarget
e: file:///home/vagrant/build/dev.datlag.burningseries/build.gradle.kts:54:22: Unresolved reference: YarnPlugin
e: file:///home/vagrant/build/dev.datlag.burningseries/build.gradle.kts:54:34: Type mismatch: inferred type is () -> Unit but Class<TypeVariable(S)!>! was expected
e: file:///home/vagrant/build/dev.datlag.burningseries/build.gradle.kts:55:9: Unresolved reference: yarn
e: file:///home/vagrant/build/dev.datlag.burningseries/build.gradle.kts:55:14: Variable expected

FAILURE: Build failed with an exception.

* Where:
Build file '/home/vagrant/build/dev.datlag.burningseries/build.gradle.kts' line: 49

* What went wrong:
Script compilation errors:

  Line 49:     tasks.withType<KotlinCompile>().configureEach {
                              ^ Unresolved reference: KotlinCompile

  Line 50:         compilerOptions {
                   ^ Unresolved reference: compilerOptions

  Line 51:             jvmTarget.set(JvmTarget.JVM_17)
                       ^ Unresolved reference: jvmTarget

  Line 51:             jvmTarget.set(JvmTarget.JVM_17)
                                     ^ Unresolved reference: JvmTarget

  Line 54:     plugins.withType<YarnPlugin> {
                                ^ Unresolved reference: YarnPlugin

  Line 54:     plugins.withType<YarnPlugin> {
                                            ^ Type mismatch: inferred type is () -> Unit but Class<TypeVariable(S)!>! was expected

  Line 55:         yarn.yarnLockAutoReplace = true
                   ^ Unresolved reference: yarn

  Line 55:         yarn.yarnLockAutoReplace = true
                        ^ Variable expected

8 errors
```
